name: Publish Website to CPanel
on:
  push:
    branches:
      - main
jobs:
  SFTP-Deploy-Action:
    name: SFTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2 
    - name: Build assets
      run: npm install && npm run build

    - name: Install PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
          php-version: '8.2' # Sesuaikan dengan versi PHP yang digunakan di project Laravel Anda
          tools: 'composer'

    - name: Install PHP dependencies
      run: composer install --no-dev --optimize-autoloader
        
    - name: Deploy to server via SFTP
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SFTP_HOST }}
        username: ${{ secrets.SFTP_USERNAME }}
        key: ${{ secrets.SFTP_PRIVATE_KEY }} # SSH Key yang sudah disimpan di Secrets GitHub
        port: 22 # Port default untuk SSH
        source: "./dist/*"  # Folder yang akan diupload (sesuaikan dengan folder build anda)
        target: "/path/to/your/remote/directory" # Direktori tujuan di server
